project:
  type: website
  output-dir: docs

website:
  title: "GeounivR 2024"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "A propos"
      - section: "INTRODUCTION"
        contents:
          - href: INTRO_programmR.html
            text: "Programmer en R"  
          - href: INTRO_pedagogique.qmd
            text: "Rédiger un cours avec R"
          - href: INTRO_importation.html
            text: "Importer des données dans R"  
      - section: "CARTO & GEOMATIQUE"
        contents:
          - href: CARTO_vecteurs.qmd
            text: "Manipulation de données vecteurs (sf)" 
          - href: CARTO_rasters.html
            text: "Manipulation de données rasters (terra)"
          - href: https://neocarto.github.io/geounivr2024/VEN1_geoviz_intro/docs/index.html
            text: "Cartographie dynamique (observable)"            
      - section: "STATISTIQUE UNIVARIEE"
        contents:
          - href: STAT1_Univariee_cours.qmd
            text: "Statistique univariée - Cours"
          - href: STAT1_Univariee_diapos.qmd
            text: "Statistique univariée - Diaporama"
      - section: "STATISTIQUE BIVARIEE"
        contents:
          - href: STAT2A_biv_quali_quali_cours.qmd
            text: "X et Y qualitatives - Cours"        
          - href: STAT2A_biv_quali_quali_diapos.qmd
            text: "X et Y qualitatives - Diaporama"
          - href: STAT2B_biv_quali_quanti_cours.qmd
            text: "Y quantitative et X qualitative - Cours" 
          - href: STAT2B_biv_quali_quanti_diapos.qmd
            text: "Y quantitative et X qualitative - Diaporama"             
          - href: STAT2C_biv_quanti_quanti_cours.qmd
            text: "X et Y quantitatives - Cours"  
          - href: STAT2C_biv_quanti_quanti_diapos.qmd
            text: "X et Y quantitatives - Diaporama" 
      - section: "STATISTIQUE MULTIVARIEE."
        contents:
          - href: EXPLO1_Prepare_data.qmd
            text: "Etape 1. Préparation des données"    
          - href: EXPLO2_Exploration_stat_carto.qmd
            text: "Etape 2. Exploration univariée"  
          - href: EXPLO3_ACP.qmd
            text: "Etape 3. Analyse en composantes principales"   
          - href: EXPLO4_CAH.qmd
            text: "Etape 4. Classification ascendante hiérarchique"              
          - href: EXPLO_gouv_2004.qmd
            text: "Synthèse : les gouvernorats en 2004"   
          - href: EXPLO_gouv_2014.qmd
            text: "Exercice : les gouvernorats en 2014"  
      - section: "MODELES DE REGRESSION"
        contents:
          - href: MOD1_Analyse_de_variance_cours.qmd
            text: "Analyse de variance simple et multiple (cours)"
          - href: MOD2_Regression_lineaire_cours.qmd
            text: "Régression linéaire simple (cours)"    
          - href: MOD3_Regression_non_lineaire_cours.qmd
            text: "Régression non linéaire (cours)" 
      - section: "ANALYSE SPATIALE"
        contents:
          - href: ANSPA_Semis_de_points_cours.qmd
            text: "Analyse d'un semis de points (cours)"  
          - href: ANSPA_Semis_de_points_diapos.qmd
            text: "Analyse d'un semis de points (diapos)"   
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/geounivR_2024
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025, FR CIST
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


